### ISSUE TITLE
Is DendroPy required as a pre-installation for the linux install?

### ISSUE THREAD

**Issue by rossmounce** [willpearse/phyloGenerator#38]
Just making sure I can run it ahead of the workshop...
I can't believe it's been over 3 years since I last looked at this! How time flies!

```
ross@ross-envy:~/workspace/pearsepg/phyloGenerator-master$ ./setupLinux.py /home/ross/workspace/pearsepg/BEASTv1.8.4/bin /home/ross/workspace/pearsepg/prank/bin/ /home/ross/workspace/pearsepg/pathd8 /home/ross/workspace/pearsepg/phylocom-4.2/src /home/ross/workspace/pearsepg/metal-linux64-1.1 /home/ross/workspace/pearsepg/trimAl/source /home/ross/workspace/pearsepg/clustalofolder/ /home/ross/workspace/pearsepg/standard-RAxML-master
Linux configuration script for phyloGenerator

Pass, as additional command line arguments, the path where you've downloaded all your files
	and *which folder contains BEAST*
	e.g., './setupLinux.py /home/will/phyloGenerator /home/will/phyloGenerator/BEAST\ v1.7.4'
Make sure all programs are executable - if unsure, make them so
	e.g., 'chmod +x NAMEOFPROGRAM'
The resulting 'requires' folder must contain only output from this script
Do not leave source code from the programs phyloGenerator uses in the same folder
	as phyloGenerator.py, or (for safety) in your output 'working directory'
	This will cause obscure-looking errors from phyloGenerator!
Checking and configuring external programs

ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/mafft': File exists
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/muscle': File exists
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/prank': Permission denied
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/clustalo': Permission denied
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/metal': Permission denied
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/trimal': Permission denied
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/phylomatic': Permission denied
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/PATHd8': File exists
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/raxml': Permission denied
ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/beast': File exists
Checking Python libraries

ln: failed to create symbolic link '/home/ross/workspace/pearsepg/phyloGenerator-master/requires/treeannotator': File exists


CONGRATULATIONS!
phyloGenerator is setup. You should now be able to run it by typing './phyloGenerator.py'
ross@ross-envy:~/workspace/pearsepg/phyloGenerator-master$ ./phyloGenerator.py
bash: ./phyloGenerator.py: Permission denied
ross@ross-envy:~/workspace/pearsepg/phyloGenerator-master$ chmod +x phyloGenerator.py 
ross@ross-envy:~/workspace/pearsepg/phyloGenerator-master$ ./phyloGenerator.pyTraceback (most recent call last):
  File "./phyloGenerator.py", line 33, in <module>
    import dendropy#To drop tips...
ImportError: No module named dendropy
ross@ross-envy:~/workspace/pearsepg/phyloGenerator-master$ ./phyloGenerator.py
Traceback (most recent call last):
  File "./phyloGenerator.py", line 33, in <module>
    import dendropy#To drop tips...
ImportError: No module named dendropy
```

**Comment by rossmounce** [comment]
Yeah, after install DendroPy, I'm in :smile: 

```
sudo -H pip install -U dendropy
```

**Comment by willpearse** [comment]
Ah right, thank you. I'll add this to the requirements...

If I were you, I'd be more interested in getting pG2 working (http://willpearse.github.io/phyloGenerator2/). The quick-start is basically it - there's not much more to it than that.

Time does, indeed, fly. I don't think we've actually met in person, so I'm looking forward to it!... :D

**Comment by rossmounce** [comment]
I had a look at pg2 but wasn't sure if it was ready for prime-time yet. I'll give that a go next...
Likewise I'm looking forward to meeting you IRL :)
